name: Automated Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Check for release commit
        id: check_release
        run: |
          if [[ "${{ github.event.head_commit.message }}" == *"release:"* ]]; then
            echo "is_release=true" >> $GITHUB_OUTPUT
            echo "release_type=$(echo "${{ github.event.head_commit.message }}" | grep -o 'release:[^[:space:]]*' | cut -d: -f2)"
          else
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Bump version
        if: steps.check_release.outputs.is_release == 'true'
        run: |
          RELEASE_TYPE="${{ steps.check_release.outputs.release_type }}"
          if [ "$RELEASE_TYPE" = "major" ]; then
            bump2version major
          elif [ "$RELEASE_TYPE" = "minor" ]; then
            bump2version minor
          else
            bump2version patch
          fi

      - name: Push changes
        if: steps.check_release.outputs.is_release == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git push origin main
          git push --tags

      - name: Create Release
        if: steps.check_release.outputs.is_release == 'true'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v$(cat VERSION)
          release_name: Release v$(cat VERSION)
          body: |
            Automated release for version $(cat VERSION)
            
            Changes in this release:
            - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false 